# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# FluidHelloWorld build for CI

trigger:
- main

pr: none

variables:
  skipComponentGovernanceDetection: true

pool: 'Main'

steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
- task: UseNode@1
  displayName: Use Node 12.x
  inputs:
    version: 12.x

# This step will be removed after the packages are on npmjs
- task: npmAuthenticate@0
  displayName: Auth
  inputs:
    workingFile: '.npmrc'
    customEndpoint: 'Offnet Packages'
- task: Npm@1
  displayName: Install
  inputs:
    command: 'custom'
    customCommand: 'ci'

- task: Npm@1
  displayName: Build
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Pipeline.Workspace)/storybook-static'
    includeRootFolder: false
    archiveType: 'tar' # Options: zip, 7z, tar, wim
    tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
    archiveFile: '$(Pipeline.Workspace)/$(Build.SourceVersion).tar.gz'
    replaceExistingArchive: true
    verbose: true # Optional
    #quiet: # Optional

- task: AzureCLI@2
  displayName: 'Upload JSON'
  inputs:
    azureSubscription: 'fluid-docs'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload -f '$(Pipeline.Workspace)/$(Build.SourceVersion).tar.gz' -c 'storybook' -n $(Build.SourceVersion).tar.gz --account-name ${{ parameters.STORAGE_ACCOUNT }} --account-key ${{ parameters.STORAGE_KEY }} --verbose

- task: AzureCLI@2
  displayName: 'Upload JSON as latest.tar.gz'
  inputs:
    azureSubscription: 'fluid-docs'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload -f '$(Pipeline.Workspace)/$(Build.SourceVersion).tar.gz' -c 'storybook' -n latest.tar.gz --account-name ${{ parameters.STORAGE_ACCOUNT }} --account-key ${{ parameters.STORAGE_KEY }} --verbose
