# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# FluidHelloWorld build for CI

trigger:
- main

pr:
- main

variables:
  skipComponentGovernanceDetection: true

pool: 'Lite'

steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
- task: UseNode@1
  displayName: Use Node 12.x
  inputs: 
    version: 12.x

- task: Npm@1
  displayName: Install
  inputs:
    command: 'custom'
    customCommand: 'install'

- task: Npm@1
  displayName: Build
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: Npm@1
  displayName: Test
  inputs:
    command: 'custom'
    customCommand: 'run test -- --reporters=default --reporters=jest-junit'

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*junit-report.xml'
    searchFolder: nyc
    mergeTestResults: true
  condition: succeededOrFailed()