# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# FluidHelloWorld build for CI

trigger:
- main

pr:
- main

variables:
  skipComponentGovernanceDetection: true

# The `resources` specify the location and version of the 1ES PT.
resources:
  repositories:
    - repository: m365Pipelines
      type: git
      name: 1ESPipelineTemplates/M365GPT
      ref: refs/tags/release
extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  # Read more: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/onboarding/overview
  template: v1/M365.Official.PipelineTemplate.yml@m365Pipelines
  parameters:
    pool:
      name: Small-1ES # This is one of the Fluid Orgs new 1ES hosted pools.
      os: linux
    sdl:
      arrow:
        # This is the service connection for the Arrow Service Connection in FluidFramework Azure DevOps organization
        # Currently we want to use different names for internal and public builds for Arrow Service Connection
        ${{ if eq(variables['System.TeamProject'], 'internal') }}:
          serviceConnection: Arrow_FluidFramework_internal
        ${{ else }}:
          serviceConnection: Arrow_FluidFramework_public
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: Run_build
        jobs:
          - job: Run_build
            steps:
              - task: ComponentGovernanceComponentDetection@0
                inputs:
                  scanType: 'Register'
                  verbosity: 'Verbose'
                  alertWarningLevel: 'High'
              - task: UseNode@1
                displayName: Use Node 12.x
                inputs:
                  version: 12.x
              - task: Npm@1
                displayName: Install
                inputs:
                  command: 'custom'
                  customCommand: 'install'

              # Remove Policy Check until folder issue is resolved
              # - task: Npm@1
              #   displayName: Policy Check
              #   inputs:
              #     command: 'custom'
              #     customCommand: 'run policy-check'

              - task: Npm@1
                displayName: Build
                inputs:
                  command: 'custom'
                  customCommand: 'run build'
              - task: Npm@1
                displayName: Test
                inputs:
                  command: 'custom'
                  customCommand: 'run test -- --reporters=default --reporters=jest-junit'
              - task: PublishTestResults@2
                displayName: Publish Test Results
                inputs:
                  testResultsFormat: 'JUnit'
                  testResultsFiles: '**/*junit-report.xml'
                  searchFolder: nyc
                  mergeTestResults: true
                condition: succeededOrFailed()
